### PR TITLE
Mark down

### PR DESCRIPTION
**Pull request by ralph-dev**
The Initial UI structure for the MarkDown Box!
image

image

(Stuck trying to align Red Dot with Text.

### CODE REVIEW

**Comment by nchaloult** [comment]
What's the red dot for? The one that you're trying to align with folder names? Is it a button?

**Comment by nchaloult** [comment]
What does everyone think about abstracting away the markdown display as its own component? Right now, the `MarkdownDisplay` component is just a styled div. If it were its own component, we could provide a list of strings for each line to display as props, making things much more modular.

**Comment by ralph-dev** [comment]
I can definitely do that for Code Clean-Up later on (i was going to do it at the start but decided to optimize later haha). 

It also depends on whether we want to have that as a prop or just pass it in as children :)

**Comment by mohammedsahl** [comment]
I think we can leave that for later if its not too crucial to the project.

**Pull request merged**
